raw: "/tmp/pycharm_project_785/MulT-EHR/physionet.org/mimiciv/hosp2"
dataset_name: "mimic4_dp"  # d: +diagnosis table; p: + procedure table
processed_path: "./data/dataset_objects/"
graph_output_path: "./data/graphs/"

all_stays_path: "./data/root/all_stays.csv"
all_diagnoses_path: "./data/root/all_diagnoses.csv"
